id: dk.fhir.ig.medcom-core
canonical: http://medcom.dk/fhir/core
name: MedComCore
title: "DK MedCom Core (R4)"
description: The DK MedCom Core IG
status: draft
version: 0.9
fhirVersion: 4.0.1
copyrightYear: 2020+
releaseLabel: Build CI
publisher:
  name: MedCom
  url: http://www.medcom.dk
jurisdiction: urn:iso:std:iso:3166#DK "Denmark"
dependencies:
  dk.fhir.ig.dk-core: current

menu:
  Table of Contents: toc.html
  Home: index.html
  Profiles: profiles.html
  Extensions: extensions.html
  Terminology: terminology.html
  Artifacts: artifacts.html
  Downloads: downloads.html

parameters:
  apply-contact: true
  apply-juristiction: true
  apply-publisher: true
